### ISSUE TITLE
发布问题

### ISSUE THREAD

**Issue by weikongkun** [zhangtianle/SpringBoot-Based-Login#1]
本地测试没有问题，打成war包之后发布到tomcat后，访问怎么会出错
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

**Comment by zhangtianle** [comment]
spring boot里面自带服务器容器，不需要发布到tomcat，maven打包后，直接java -jar xxx.jar运行即可。参考:https://github.com/zhangtianle/SpringBoot-Based-Login#%E9%A1%B9%E7%9B%AE%E6%89%93%E5%8C%85%E8%BF%90%E8%A1%8C

**Comment by weikongkun** [comment]
想问一下，如果我想打成war包，发布到云服务器上的tomcat，怎么发布

**Comment by weikongkun** [comment]
本地是可以运行的

**Comment by zhangtianle** [comment]
1、如果要在服务上运行，和本地是一样的，在服务器上启动一个守护进程  nohup java -jar xxx.jar &
2、发布到tomcat中我没有试过，你可以参考下面的链接试试
https://blog.csdn.net/james_wade63/article/details/51009423
